### ISSUE TITLE
sklearn-compatible interface

### ISSUE THREAD

**Issue by 34j** [pyg-team/pytorch-frame#147]
I think it would be great to have this feature, as I think sklearn is often used for tabular data. I tried to use skorch, but skorch does not allow TensorFrames and did not work well.

(`examples/tutorial.py`)
```python
from skorch import NeuralNetClassifier

net = NeuralNetClassifier(module=model, max_epochs=args.epochs, lr=args.lr, 
                            device=device, batch_size=args.batch_size, 
                            classes=dataset.num_classes, iterator_train=DataLoader,
                            iterator_valid=DataLoader, train_split=None)
net.fit(train_dataset, y=None)
```
```shell
Traceback (most recent call last):
  File "\examples\tutorial.py", line 346, in <module>
    net.fit(train_dataset, y=None)
  File "\site-packages\skorch\classifier.py", line 165, in fit
    return super(NeuralNetClassifier, self).fit(X, y, **fit_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\skorch\net.py", line 1319, in fit
    self.partial_fit(X, y, **fit_params)
  File "\site-packages\skorch\net.py", line 1278, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "\site-packages\skorch\net.py", line 1190, in fit_loop
    self.run_single_epoch(iterator_train, training=True, prefix="train",
  File "\site-packages\skorch\net.py", line 1226, in run_single_epoch
    step = step_fn(batch, **fit_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\skorch\net.py", line 1105, in train_step
    self._step_optimizer(step_fn)
  File "\site-packages\skorch\net.py", line 1060, in _step_optimizer
    optimizer.step(step_fn)
  File "\site-packages\torch\optim\optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\torch\optim\optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\torch\optim\sgd.py", line 66, in step
    loss = closure()
           ^^^^^^^^^
  File "\site-packages\skorch\net.py", line 1094, in step_fn
    step = self.train_step_single(batch, **fit_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\skorch\net.py", line 993, in train_step_single
    y_pred = self.infer(Xi, **fit_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\skorch\net.py", line 1517, in infer
    x = to_tensor(x, device=self.device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\skorch\utils.py", line 104, in to_tensor
    return [to_tensor_(x) for x in X]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\skorch\utils.py", line 104, in <listcomp>
    return [to_tensor_(x) for x in X]
            ^^^^^^^^^^^^^
  File "\site-packages\skorch\utils.py", line 118, in to_tensor
    raise TypeError("Cannot convert this data type to a torch tensor.")
TypeError: Cannot convert this data type to a torch tensor.
```
I think the following changes are needed:

- Add an ability to convert from DataFrame to TensorFrame without much prior information.
- Create a wrapper that passes Tensor to skorch or create a scikit-learn compatible estimator specifically for this package.

I am sorry, but I cannot take much time to assist in creating this feature, so if it is not possible, please close it.

**Comment by yiweny** [comment]
You can convert a `DataFrame` to `TensorFrame` easily with 
```
dataset = Dataset(df, col_to_stype=col_to_stype, target_col="y")
dataset.tensor_frame
```
See [tutorial](https://pytorch-frame.readthedocs.io/en/latest/get_started/introduction.html).

**Comment by weihua916** [comment]
Thanks for your suggestion! I think this is great to add. Setting this as P2 feature, as we first want to prioritize more stype support https://github.com/pyg-team/pytorch-frame/issues/88.

**Comment by MacOS** [comment]
Is someone already working on that?

**Comment by weihua916** [comment]
No, as far as I know. Let us know if you are interested!

**Comment by MacOS** [comment]
Yes, I'm interested.

**Comment by weihua916** [comment]
@MacOS Great, thank you! It'd be good to complete this feature by the end of January. Would that be possible?

**Comment by MacOS** [comment]
@weihua916 As of now, yes.

**Comment by 34j** [comment]
I have tried this and it seems to be very difficult. 
As a quick fix that isn't pretty, the following seems necessary:

- Rewrite `to_tensor_` to bypass `TensorFrame.
- Add `index = torch.sensor(index)` to `torch_frame.DataLoader.collapse_fn` to make it return `TensorFrame` instead of `list[TensorFrame]`.

However, I don't know how to pass the validation dataset.

**Comment by MacOS** [comment]
:thinking:

Thank you for looking into this, @34j! I was about to start working on it.

> Add an ability to convert from DataFrame to TensorFrame without much prior information.

I would have simply converted the ``DataFrame`` to ``TensorFrame`` internally, work with it, and if requested, return the ``DataFrame`` again. This means, of course, that one has to track what was given. Or am I missing something?

> Create a wrapper that passes Tensor to skorch or create a scikit-learn compatible estimator specifically for this package.

This seems to be very big and unrealistic because we would have to make **all** estimators compatible with scikit-learn, which is a lot to ask for. At the moment, ``scikit-learn`` is an **optional** dependency.

May I ask you, @34j, to post a self-contained example (or examples) that what qualify **pytorch-frame** as being **sklearn-compatible**?

**Comment by MacOS** [comment]
@34j Is fine with me!

So we drop the second part of your request then, correct?

**Comment by MacOS** [comment]
Heads up everyone, I started working on it. I already merge the PR draft of @34j into my fork.

Would be nice if you guys would be available in case I have questions. :)

**Comment by 34j** [comment]
May I ask you what is your question

**Comment by 34j** [comment]
> Heads up everyone, I started working on it. I already merge the PR draft of @34j into my fork.
> 
> Would be nice if you guys would be available in case I have questions. :)

May I ask you what is your question

**Comment by MacOS** [comment]
So far none. I meant just in case.

Sorry for the delay at all, but I had personal matters to deal with. I'm confident that I can submit a PR this month.

**Comment by MacOS** [comment]
Hi all,

short update, unfortunately, I got sick, hence again a delay. Should I still work on it?

**Comment by qychen2001** [comment]
> Hi all,
> 
> short update, unfortunately, I got sick, hence again a delay. Should I still work on it?

I think it should continue. Are you still working on this part? Otherwise I can take over.

**Comment by MacOS** [comment]
Yes, still working on it @qychen2001!

**Comment by qychen2001** [comment]
> Yes, still working on it @qychen2001!

That's great! This feature is really important, looking forward to your PR.

**Comment by 34j** [comment]
Sorry but I have almost completed this feature in #375 and am just waiting for @weihua916 's review.

**Comment by qychen2001** [comment]
> Sorry but I have almost completed this feature by myself in #375 (as MacOS seemed to be sick) and am just waiting for @weihua916 's review. However, the styling work for pre-commit by MacOS I referred certainly helped this.

That's fantastic! But I'm still concerned about the relationship between skorch and sklearn, can your PR directly support models in sklearn such as svm?

**Comment by 34j** [comment]
Excuse me but what do you mean by relationship? skorch works perfectly, trust me plz

**Comment by 34j** [comment]
> can your PR directly support models in sklearn such as svm?

sklearn models already has sklearn-compatible interface apparently
